#!/bin/bash
##生成NE40命令
case $1 in
	-C|--ne40-config)
		echo  "`sed 's/^/dis cu | in /;s/\/.*/ /g' $2`"
		;;
	-M|--mx960-ospf)
		echo "`sed 's/^/sh route /; s/$/ |match "OSPF|Static" |match \\\*/g' $2`"
		;;
	-D|--ne40-del)
		echo  "`sed 's/^/undo ip route-static /;s/\// /g' $2`"
		;;
	-A|--aspath)
		echo "show route aspath-regex .*$2.* | match \* | except ^10\. | except ^14\. | except MED | match from | no-more"
		;;
	*)
		echo "help context"
    ;;
esac
